// Bindings generated by `windows-bindgen` 0.62.1

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[inline]
pub unsafe fn DCompositionCreateDevice<P0, T>(dxgidevice: P0) -> windows_core::Result<T>
where
    P0: windows_core::Param<::windows::Win32::Graphics::Dxgi::IDXGIDevice>,
    T: windows_core::Interface,
{
    windows_core::link!("dcomp.dll" "system" fn DCompositionCreateDevice(dxgidevice : * mut core::ffi::c_void, iid : *const windows_core::GUID, dcompositiondevice : *mut *mut core::ffi::c_void) -> windows_core::HRESULT);
    let mut result__ = core::ptr::null_mut();
    unsafe {
        DCompositionCreateDevice(dxgidevice.param().abi(), &T::IID, &mut result__)
            .and_then(|| windows_core::Type::from_abi(result__))
    }
}
windows_core::imp::define_interface!(
    IDCompositionDevice,
    IDCompositionDevice_Vtbl,
    0xc37ea93a_e7aa_450d_b16f_9746cb0407f3
);
windows_core::imp::interface_hierarchy!(IDCompositionDevice, windows_core::IUnknown);
impl IDCompositionDevice {
    pub unsafe fn Commit(&self) -> windows_core::Result<()> {
        unsafe {
            (windows_core::Interface::vtable(self).Commit)(windows_core::Interface::as_raw(self))
                .ok()
        }
    }
    pub unsafe fn CreateTargetForHwnd(
        &self,
        hwnd: ::windows::Win32::Foundation::HWND,
        topmost: bool,
    ) -> windows_core::Result<IDCompositionTarget> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).CreateTargetForHwnd)(
                windows_core::Interface::as_raw(self),
                hwnd,
                topmost.into(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub unsafe fn CreateVisual(&self) -> windows_core::Result<IDCompositionVisual> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).CreateVisual)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IDCompositionDevice_Vtbl {
    pub base__: windows_core::IUnknown_Vtbl,
    pub Commit: unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
    pub WaitForCommitCompletion:
        unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
    GetFrameStatistics: usize,
    pub CreateTargetForHwnd: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        ::windows::Win32::Foundation::HWND,
        windows_core::BOOL,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub CreateVisual: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    CreateSurface: usize,
    CreateVirtualSurface: usize,
    pub CreateSurfaceFromHandle: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        ::windows::Win32::Foundation::HANDLE,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub CreateSurfaceFromHwnd: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        ::windows::Win32::Foundation::HWND,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    CreateTranslateTransform: usize,
    CreateScaleTransform: usize,
    CreateRotateTransform: usize,
    CreateSkewTransform: usize,
    CreateMatrixTransform: usize,
    CreateTransformGroup: usize,
    CreateTranslateTransform3D: usize,
    CreateScaleTransform3D: usize,
    CreateRotateTransform3D: usize,
    CreateMatrixTransform3D: usize,
    CreateTransform3DGroup: usize,
    CreateEffectGroup: usize,
    CreateRectangleClip: usize,
    CreateAnimation: usize,
    pub CheckDeviceState: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut windows_core::BOOL,
    ) -> windows_core::HRESULT,
}
impl windows_core::RuntimeName for IDCompositionDevice {}
windows_core::imp::define_interface!(
    IDCompositionTarget,
    IDCompositionTarget_Vtbl,
    0xeacdd04c_117e_4e17_88f4_d1b12b0e3d89
);
windows_core::imp::interface_hierarchy!(IDCompositionTarget, windows_core::IUnknown);
impl IDCompositionTarget {
    pub unsafe fn SetRoot<P0>(&self, visual: P0) -> windows_core::Result<()>
    where
        P0: windows_core::Param<IDCompositionVisual>,
    {
        unsafe {
            (windows_core::Interface::vtable(self).SetRoot)(
                windows_core::Interface::as_raw(self),
                visual.param().abi(),
            )
            .ok()
        }
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IDCompositionTarget_Vtbl {
    pub base__: windows_core::IUnknown_Vtbl,
    pub SetRoot: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
impl windows_core::RuntimeName for IDCompositionTarget {}
windows_core::imp::define_interface!(
    IDCompositionVisual,
    IDCompositionVisual_Vtbl,
    0x4d93059d_097b_4651_9a60_f0f25116e2f3
);
windows_core::imp::interface_hierarchy!(IDCompositionVisual, windows_core::IUnknown);
impl IDCompositionVisual {
    pub unsafe fn SetContent<P0>(&self, content: P0) -> windows_core::Result<()>
    where
        P0: windows_core::Param<windows_core::IUnknown>,
    {
        unsafe {
            (windows_core::Interface::vtable(self).SetContent)(
                windows_core::Interface::as_raw(self),
                content.param().abi(),
            )
            .ok()
        }
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IDCompositionVisual_Vtbl {
    pub base__: windows_core::IUnknown_Vtbl,
    SetOffsetX: usize,
    pub SetOffsetX2:
        unsafe extern "system" fn(*mut core::ffi::c_void, f32) -> windows_core::HRESULT,
    SetOffsetY: usize,
    pub SetOffsetY2:
        unsafe extern "system" fn(*mut core::ffi::c_void, f32) -> windows_core::HRESULT,
    SetTransform: usize,
    pub SetTransform2: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *const core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetTransformParent: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    SetEffect: usize,
    SetBitmapInterpolationMode: usize,
    SetBorderMode: usize,
    SetClip: usize,
    SetClip2: usize,
    pub SetContent: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub AddVisual: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        windows_core::BOOL,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub RemoveVisual: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub RemoveAllVisuals:
        unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
    SetCompositeMode: usize,
}
impl windows_core::RuntimeName for IDCompositionVisual {}

// ---------------------------------------------------------------------------
// Hand-written supplements for the transparent-popup path. The vendored
// `windows` crate is a trimmed generation that omits any symbol upstream
// makepad never referenced, so the constants and the factory-composition
// method below are absent from it even though the underlying vtable slot
// (CreateSwapChainForComposition) is present. Values match dxgicommon.h /
// winuser.h; the extension method mirrors the crate's own inherent-method
// codegen, dispatching through the existing pub vtable field.

use ::windows::Win32::Graphics::Dxgi::Common::DXGI_ALPHA_MODE;
use ::windows::Win32::Graphics::Dxgi::{
    IDXGIFactory2, IDXGISwapChain1, DXGI_SCALING, DXGI_SWAP_CHAIN_DESC1,
};
use ::windows::Win32::UI::WindowsAndMessaging::WINDOW_EX_STYLE;

pub const DXGI_ALPHA_MODE_PREMULTIPLIED: DXGI_ALPHA_MODE = DXGI_ALPHA_MODE(1);
pub const DXGI_SCALING_STRETCH: DXGI_SCALING = DXGI_SCALING(0);
pub const WS_EX_NOREDIRECTIONBITMAP: WINDOW_EX_STYLE = WINDOW_EX_STYLE(0x00200000);

pub trait IDXGIFactory2CompositionExt {
    /// Create a composited swapchain (no HWND target); it is presented via a
    /// DirectComposition visual. Restrict-to-output is always null here.
    unsafe fn CreateSwapChainForComposition<P0>(
        &self,
        device: P0,
        desc: *const DXGI_SWAP_CHAIN_DESC1,
    ) -> windows_core::Result<IDXGISwapChain1>
    where
        P0: windows_core::Param<windows_core::IUnknown>;
}

impl IDXGIFactory2CompositionExt for IDXGIFactory2 {
    unsafe fn CreateSwapChainForComposition<P0>(
        &self,
        device: P0,
        desc: *const DXGI_SWAP_CHAIN_DESC1,
    ) -> windows_core::Result<IDXGISwapChain1>
    where
        P0: windows_core::Param<windows_core::IUnknown>,
    {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).CreateSwapChainForComposition)(
                windows_core::Interface::as_raw(self),
                device.param().abi(),
                desc,
                core::ptr::null_mut(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
}
